/* Contenido editorial separado de la logica del modulo. */
window.ToolsCatalogMarkup = [
  "<div class=\"category\" data-cat=\"diseno\">",
  "  <div class=\"cat-header\">",
  "    <span class=\"cat-label\">01</span>",
  "    <span class=\"cat-title\">Diseño Gráfico</span>",
  "    <div class=\"cat-line\"></div>",
  "    <span class=\"cat-count\">4</span>",
  "  </div>",
  "",
  "  <div class=\"tool-card bc-canva\" data-key=\"canva\">",
  "    <div class=\"tool-main\">",
  "      <div class=\"tool-logo lb-canva\"><img src=\"https://cdn.simpleicons.org/canva/ffffff\" alt=\"Canva\" onerror=\"this.style.display='none'\"></div>",
  "      <div class=\"tool-info\">",
  "        <div class=\"tool-header\"><span class=\"tool-name\">Canva</span><span class=\"tool-badge\">⭐ Imprescindible</span></div>",
  "        <div class=\"tool-tagline\">Diseñá publicaciones, flyers, logos y más sin saber diseño</div>",
  "        <div class=\"tool-desc\">La herramienta de diseño más popular para emprendedores. Miles de plantillas listas para redes sociales, historias, catálogos y tarjetas de presentación. Muy fácil e intuitiva.</div>",
  "        <div class=\"tool-features\">",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Plantillas para Instagram, Facebook, WhatsApp y más</span></div>",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Guardá tus colores y logo para mantener consistencia</span></div>",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>IA para generar imágenes, quitar fondos y redactar textos</span></div>",
  "        </div>",
  "      </div>",
  "    </div>",
  "    <div class=\"tool-footer\">",
  "      <div class=\"platforms\"><span class=\"plat\">🌐 Web</span><span class=\"plat\">📱 iOS</span><span class=\"plat\">🤖 Android</span></div>",
  "      <span class=\"tool-tip\">💡 Creá una \"carpeta de marca\" con tus colores y logo para que todo sea consistente.</span>",
  "      <a href=\"https://canva.com\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"visit-btn\">Abrir →</a>",
  "    </div>",
  "  </div>",
  "",
  "  <div class=\"tool-card bc-adobe\" data-key=\"adobe-express\">",
  "    <div class=\"tool-main\">",
  "      <div class=\"tool-logo lb-adobe\"><img src=\"https://cdn.simpleicons.org/adobe/ffffff\" alt=\"Adobe Express\" onerror=\"this.style.display='none'\"></div>",
  "      <div class=\"tool-info\">",
  "        <div class=\"tool-header\"><span class=\"tool-name\">Adobe Express</span><span class=\"tool-badge\">Alternativa</span></div>",
  "        <div class=\"tool-tagline\">Efectos y fuentes premium de Adobe, completamente gratis</div>",
  "        <div class=\"tool-desc\">La versión gratuita de Adobe para diseño rápido. Tiene tipografías y efectos de texto exclusivos que no están en Canva. Ideal si buscás una estética diferente y más refinada.</div>",
  "        <div class=\"tool-features\">",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Cientos de fuentes premium de Adobe disponibles gratis</span></div>",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Animaciones para publicaciones que se mueven</span></div>",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Integración con Adobe Stock para imágenes sin cargo</span></div>",
  "        </div>",
  "      </div>",
  "    </div>",
  "    <div class=\"tool-footer\">",
  "      <div class=\"platforms\"><span class=\"plat\">🌐 Web</span><span class=\"plat\">📱 iOS</span><span class=\"plat\">🤖 Android</span></div>",
  "      <span class=\"tool-tip\">💡 Probalo si querés tipografías más originales que las de Canva.</span>",
  "      <a href=\"https://express.adobe.com\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"visit-btn\">Abrir →</a>",
  "    </div>",
  "  </div>",
  "",
  "  <div class=\"tool-card bc-photopea\" data-key=\"photopea\">",
  "    <div class=\"tool-main\">",
  "      <div class=\"tool-logo lb-photopea\"><img src=\"https://cdn.simpleicons.org/photopea/ffffff\" alt=\"Photopea\" onerror=\"this.style.display='none'\"></div>",
  "      <div class=\"tool-info\">",
  "        <div class=\"tool-header\"><span class=\"tool-name\">Photopea</span><span class=\"tool-badge\">Avanzado</span></div>",
  "        <div class=\"tool-tagline\">Photoshop gratis que funciona directo en el navegador</div>",
  "        <div class=\"tool-desc\">Un Photoshop completo sin instalar nada. Ideal para retocar fotos de productos, quitar fondos complejos o hacer ediciones que Canva no permite. Abre archivos .PSD.</div>",
  "        <div class=\"tool-features\">",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Edición avanzada de imágenes sin instalar software</span></div>",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Abre archivos de Photoshop (.PSD) directamente</span></div>",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Quita fondos, ajusta colores y aplica filtros profesionales</span></div>",
  "        </div>",
  "      </div>",
  "    </div>",
  "    <div class=\"tool-footer\">",
  "      <div class=\"platforms\"><span class=\"plat\">🌐 Web</span></div>",
  "      <span class=\"tool-tip\">💡 Usalo cuando necesitás editar una foto de producto con más precisión que Canva.</span>",
  "      <a href=\"https://photopea.com\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"visit-btn\">Abrir →</a>",
  "    </div>",
  "  </div>",
  "",
  "  <div class=\"tool-card bc-removebg\" data-key=\"remove-bg\">",
  "    <div class=\"tool-main\">",
  "      <div class=\"tool-logo lb-removebg\"><span class=\"logo-emoji\">✂️</span></div>",
  "      <div class=\"tool-info\">",
  "        <div class=\"tool-header\"><span class=\"tool-name\">Remove.bg</span><span class=\"tool-badge\">Específico</span></div>",
  "        <div class=\"tool-tagline\">Eliminá el fondo de cualquier foto en segundos con IA</div>",
  "        <div class=\"tool-desc\">Subís una foto y en segundos la IA elimina el fondo automáticamente. Perfecto para fotos de catálogo, stickers o publicaciones con fondo de color liso.</div>",
  "        <div class=\"tool-features\">",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Elimina fondos con un solo click, sin edición manual</span></div>",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Funciona excelente con personas, productos y logos</span></div>",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Descarga gratis en resolución estándar (suficiente para redes)</span></div>",
  "        </div>",
  "      </div>",
  "    </div>",
  "    <div class=\"tool-footer\">",
  "      <div class=\"platforms\"><span class=\"plat\">🌐 Web</span><span class=\"plat\">📱 iOS</span><span class=\"plat\">🤖 Android</span></div>",
  "      <span class=\"tool-tip\">💡 Combinalo con Canva: quitá el fondo acá y luego usá la imagen en tus diseños.</span>",
  "      <a href=\"https://remove.bg\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"visit-btn\">Abrir →</a>",
  "    </div>",
  "  </div>",
  "</div>",
  "",
  "<!-- ══ VIDEO ══ -->",
  "<div class=\"category\" data-cat=\"video\">",
  "  <div class=\"cat-header\">",
  "    <span class=\"cat-label\">02</span>",
  "    <span class=\"cat-title\">Edición de Video</span>",
  "    <div class=\"cat-line\"></div>",
  "    <span class=\"cat-count\">4</span>",
  "  </div>",
  "",
  "  <div class=\"tool-card bc-edits\" data-key=\"edits\">",
  "    <div class=\"tool-main\">",
  "      <div class=\"tool-logo lb-edits\"><img src=\"https://cdn.simpleicons.org/instagram/ffffff\" alt=\"Edits by Instagram\" onerror=\"this.style.display='none'\"></div>",
  "      <div class=\"tool-info\">",
  "        <div class=\"tool-header\"><span class=\"tool-name\">Edits by Instagram</span><span class=\"tool-badge\">🆕 Nuevo</span></div>",
  "        <div class=\"tool-tagline\">El editor de Reels oficial de Meta, diseñado para Instagram</div>",
  "        <div class=\"tool-desc\">La apuesta de Meta para competirle a CapCut. Editor de video pensado 100% para Reels: acceso anticipado a audios en tendencia, animaciones y efectos dentro del ecosistema de Instagram. Al ser de Meta, los videos pueden tener mejor alcance orgánico.</div>",
  "        <div class=\"tool-features\">",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Acceso anticipado a los audios que están siendo tendencia en Instagram</span></div>",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Funciona sin conexión — editás aunque no tengas señal</span></div>",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Videos editados acá pueden tener mejor rendimiento en el algoritmo de IG</span></div>",
  "        </div>",
  "      </div>",
  "    </div>",
  "    <div class=\"tool-footer\">",
  "      <div class=\"platforms\"><span class=\"plat\">📱 iOS</span><span class=\"plat\">🤖 Android</span></div>",
  "      <span class=\"tool-tip\">💡 Si publicás en Instagram, probá Edits antes que CapCut — el algoritmo premia los videos hechos con herramientas propias.</span>",
  "      <a href=\"https://www.instagram.com/edits/\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"visit-btn\">Abrir →</a>",
  "    </div>",
  "  </div>",
  "",
  "  <div class=\"tool-card bc-capcut\" data-key=\"capcut\">",
  "    <div class=\"tool-main\">",
  "      <div class=\"tool-logo lb-capcut\"><span class=\"logo-emoji\">🎬</span></div>",
  "      <div class=\"tool-info\">",
  "        <div class=\"tool-header\"><span class=\"tool-name\">CapCut</span><span class=\"tool-badge\">⭐ Imprescindible</span></div>",
  "        <div class=\"tool-tagline\">El editor de Reels y videos cortos más popular del mundo</div>",
  "        <div class=\"tool-desc\">Herramienta número uno para hacer Reels y TikToks desde el celular. Plantillas de video listas, subtítulos automáticos en español, música, efectos y transiciones. Muy fácil aunque nunca hayas editado un video.</div>",
  "        <div class=\"tool-features\">",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Subtítulos automáticos en español con un solo toque</span></div>",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Plantillas de video viral listas para adaptar a tu contenido</span></div>",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Exporta en la resolución perfecta para Instagram, TikTok y YouTube</span></div>",
  "        </div>",
  "      </div>",
  "    </div>",
  "    <div class=\"tool-footer\">",
  "      <div class=\"platforms\"><span class=\"plat\">📱 iOS</span><span class=\"plat\">🤖 Android</span><span class=\"plat\">🌐 Web</span></div>",
  "      <span class=\"tool-tip\">💡 Activá los subtítulos automáticos — el 80% de la gente ve videos sin sonido.</span>",
  "      <a href=\"https://capcut.com\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"visit-btn\">Abrir →</a>",
  "    </div>",
  "  </div>",
  "",
  "  <div class=\"tool-card bc-inshot\" data-key=\"inshot\">",
  "    <div class=\"tool-main\">",
  "      <div class=\"tool-logo lb-inshot\"><img src=\"https://cdn.simpleicons.org/inshot/ffffff\" alt=\"InShot\" onerror=\"this.style.display='none'\"></div>",
  "      <div class=\"tool-info\">",
  "        <div class=\"tool-header\"><span class=\"tool-name\">InShot</span><span class=\"tool-badge\">Fácil</span></div>",
  "        <div class=\"tool-tagline\">Edición de video simple y rápida desde el celular</div>",
  "        <div class=\"tool-desc\">Más sencillo que CapCut. Ideal para recortar videos, agregar música, texto y filtros sin complicarse. Muy bueno para historias de Instagram y videos cortos del día a día.</div>",
  "        <div class=\"tool-features\">",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Recortá, unís y ajustá velocidad en segundos</span></div>",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Ajusta automáticamente el formato para cada red social</span></div>",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Música libre de derechos incluida</span></div>",
  "        </div>",
  "      </div>",
  "    </div>",
  "    <div class=\"tool-footer\">",
  "      <div class=\"platforms\"><span class=\"plat\">📱 iOS</span><span class=\"plat\">🤖 Android</span></div>",
  "      <span class=\"tool-tip\">💡 Si CapCut te parece complicado, empezá con InShot — menos opciones, más intuitivo.</span>",
  "      <a href=\"https://inshot.com\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"visit-btn\">Abrir →</a>",
  "    </div>",
  "  </div>",
  "",
  "  <div class=\"tool-card bc-clipchamp\" data-key=\"clipchamp\">",
  "    <div class=\"tool-main\">",
  "      <div class=\"tool-logo lb-clipchamp\"><img src=\"https://cdn.simpleicons.org/clipchamp/ffffff\" alt=\"Clipchamp\" onerror=\"this.style.display='none'\"></div>",
  "      <div class=\"tool-info\">",
  "        <div class=\"tool-header\"><span class=\"tool-name\">Clipchamp</span><span class=\"tool-badge\">Computadora</span></div>",
  "        <div class=\"tool-tagline\">Editor de video de Microsoft, gratis en Windows</div>",
  "        <div class=\"tool-desc\">Si tenés Windows ya lo tenés instalado. Permite editar videos con varias pistas, agregar subtítulos y exportar en buena calidad sin marcas de agua.</div>",
  "        <div class=\"tool-features\">",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Viene incluido en Windows 11 — no necesitás instalar nada</span></div>",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Edición en múltiples pistas de video y audio</span></div>",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Exporta en 1080p sin marca de agua en el plan gratuito</span></div>",
  "        </div>",
  "      </div>",
  "    </div>",
  "    <div class=\"tool-footer\">",
  "      <div class=\"platforms\"><span class=\"plat\">🌐 Web</span><span class=\"plat\">💻 Windows</span></div>",
  "      <span class=\"tool-tip\">💡 Buscalo en el menú Inicio de Windows si estás en una PC.</span>",
  "      <a href=\"https://clipchamp.com\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"visit-btn\">Abrir →</a>",
  "    </div>",
  "  </div>",
  "</div>",
  "",
  "<!-- ══ INSPIRACIÓN ══ -->",
  "<div class=\"category\" data-cat=\"inspiracion\">",
  "  <div class=\"cat-header\">",
  "    <span class=\"cat-label\">03</span>",
  "    <span class=\"cat-title\">Inspiración Visual</span>",
  "    <div class=\"cat-line\"></div>",
  "    <span class=\"cat-count\">2</span>",
  "  </div>",
  "",
  "  <div class=\"tool-card bc-pinterest\" data-key=\"pinterest\">",
  "    <div class=\"tool-main\">",
  "      <div class=\"tool-logo lb-pinterest\"><img src=\"https://cdn.simpleicons.org/pinterest/ffffff\" alt=\"Pinterest\" onerror=\"this.style.display='none'\"></div>",
  "      <div class=\"tool-info\">",
  "        <div class=\"tool-header\"><span class=\"tool-name\">Pinterest</span><span class=\"tool-badge\">⭐ Imprescindible</span></div>",
  "        <div class=\"tool-tagline\">El mejor buscador visual de inspiración para tu marca</div>",
  "        <div class=\"tool-desc\">No es solo una red social — es el mejor lugar para encontrar inspiración visual: paletas de colores, estilos de fotos, packaging, logos, estéticas de feed. Guardás todo en tableros organizados.</div>",
  "        <div class=\"tool-features\">",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Buscá \"identidad visual [tu rubro]\" y encontrás miles de ideas</span></div>",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Tableros para organizar referencias de marca por tema</span></div>",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>También sirve para publicar y vender tus productos</span></div>",
  "        </div>",
  "      </div>",
  "    </div>",
  "    <div class=\"tool-footer\">",
  "      <div class=\"platforms\"><span class=\"plat\">🌐 Web</span><span class=\"plat\">📱 iOS</span><span class=\"plat\">🤖 Android</span></div>",
  "      <span class=\"tool-tip\">💡 Buscá \"moodboard [tu rubro]\" para encontrar la estética exacta que querés.</span>",
  "      <a href=\"https://pinterest.com\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"visit-btn\">Abrir →</a>",
  "    </div>",
  "  </div>",
  "",
  "  <div class=\"tool-card bc-behance\" data-key=\"behance\">",
  "    <div class=\"tool-main\">",
  "      <div class=\"tool-logo lb-behance\"><img src=\"https://cdn.simpleicons.org/behance/ffffff\" alt=\"Behance\" onerror=\"this.style.display='none'\"></div>",
  "      <div class=\"tool-info\">",
  "        <div class=\"tool-header\"><span class=\"tool-name\">Behance</span><span class=\"tool-badge\">Diseño profesional</span></div>",
  "        <div class=\"tool-tagline\">Portafolios de diseñadores de todo el mundo</div>",
  "        <div class=\"tool-desc\">La red de Adobe donde diseñadores publican sus trabajos. Ideal para buscar inspiración en logos, packaging e identidades de marca de nivel profesional.</div>",
  "        <div class=\"tool-features\">",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Buscá \"brand identity [tu rubro]\" para ver logos y diseños reales</span></div>",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Proyectos de branding completos con proceso incluido</span></div>",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Podés contactar diseñadores para pedirles trabajo freelance</span></div>",
  "        </div>",
  "      </div>",
  "    </div>",
  "    <div class=\"tool-footer\">",
  "      <div class=\"platforms\"><span class=\"plat\">🌐 Web</span><span class=\"plat\">📱 iOS</span></div>",
  "      <span class=\"tool-tip\">💡 Compartí links de Behance como referencias cuando le pedís algo a un diseñador.</span>",
  "      <a href=\"https://behance.net\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"visit-btn\">Abrir →</a>",
  "    </div>",
  "  </div>",
  "</div>",
  "",
  "<!-- ══ IMÁGENES ══ -->",
  "<div class=\"category\" data-cat=\"imagenes\">",
  "  <div class=\"cat-header\">",
  "    <span class=\"cat-label\">04</span>",
  "    <span class=\"cat-title\">Imágenes y Recursos Gratuitos</span>",
  "    <div class=\"cat-line\"></div>",
  "    <span class=\"cat-count\">4</span>",
  "  </div>",
  "",
  "  <div class=\"tool-card bc-unsplash\" data-key=\"unsplash\">",
  "    <div class=\"tool-main\">",
  "      <div class=\"tool-logo lb-unsplash\"><img src=\"https://cdn.simpleicons.org/unsplash/ffffff\" alt=\"Unsplash\" onerror=\"this.style.display='none'\"></div>",
  "      <div class=\"tool-info\">",
  "        <div class=\"tool-header\"><span class=\"tool-name\">Unsplash</span><span class=\"tool-badge\">Fotos</span></div>",
  "        <div class=\"tool-tagline\">Fotos profesionales gratis, sin derechos de autor</div>",
  "        <div class=\"tool-desc\">Banco de fotos de alta calidad completamente gratuitas. Más de 3 millones de imágenes que podés usar en publicaciones, diseños y materiales de tu negocio sin pedir permiso.</div>",
  "        <div class=\"tool-features\">",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Sin marca de agua y en alta resolución</span></div>",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Se integra directamente con Canva para buscar desde ahí</span></div>",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Podés usarlas comercialmente sin pagar nada</span></div>",
  "        </div>",
  "      </div>",
  "    </div>",
  "    <div class=\"tool-footer\">",
  "      <div class=\"platforms\"><span class=\"plat\">🌐 Web</span></div>",
  "      <span class=\"tool-tip\">💡 Usá fotos de Unsplash como fondo cuando no tenés fotos propias de buena calidad.</span>",
  "      <a href=\"https://unsplash.com\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"visit-btn\">Abrir →</a>",
  "    </div>",
  "  </div>",
  "",
  "  <div class=\"tool-card bc-pexels\" data-key=\"pexels\">",
  "    <div class=\"tool-main\">",
  "      <div class=\"tool-logo lb-pexels\"><img src=\"https://cdn.simpleicons.org/pexels/ffffff\" alt=\"Pexels\" onerror=\"this.style.display='none'\"></div>",
  "      <div class=\"tool-info\">",
  "        <div class=\"tool-header\"><span class=\"tool-name\">Pexels</span><span class=\"tool-badge\">Fotos y video</span></div>",
  "        <div class=\"tool-tagline\">Fotos y videos cortos gratuitos para tus publicaciones</div>",
  "        <div class=\"tool-desc\">Como Unsplash pero también tiene videos cortos gratuitos. Muy útil para usar como fondo en Reels o Stories sin tener que grabar vos mismo.</div>",
  "        <div class=\"tool-features\">",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Videos y fotos sin derechos en alta calidad</span></div>",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>App móvil para descargar directo al celular</span></div>",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Se integra con Canva y CapCut directamente</span></div>",
  "        </div>",
  "      </div>",
  "    </div>",
  "    <div class=\"tool-footer\">",
  "      <div class=\"platforms\"><span class=\"plat\">🌐 Web</span><span class=\"plat\">📱 iOS</span><span class=\"plat\">🤖 Android</span></div>",
  "      <span class=\"tool-tip\">💡 Bajá un video de fondo de tu rubro y usalo en Reels con texto encima — ahorra mucho tiempo.</span>",
  "      <a href=\"https://pexels.com\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"visit-btn\">Abrir →</a>",
  "    </div>",
  "  </div>",
  "",
  "  <div class=\"tool-card bc-flaticon\" data-key=\"flaticon\">",
  "    <div class=\"tool-main\">",
  "      <div class=\"tool-logo lb-flaticon\"><span class=\"logo-emoji\">⭐</span></div>",
  "      <div class=\"tool-info\">",
  "        <div class=\"tool-header\"><span class=\"tool-name\">Flaticon</span><span class=\"tool-badge\">Íconos</span></div>",
  "        <div class=\"tool-tagline\">Millones de íconos gratuitos para tus diseños</div>",
  "        <div class=\"tool-desc\">La biblioteca de íconos más grande del mundo. Perfecta para agregar pequeños gráficos a tus publicaciones, listas de servicios, catálogos o presentaciones.</div>",
  "        <div class=\"tool-features\">",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Íconos en PNG, SVG y múltiples estilos</span></div>",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Cambiá el color antes de descargar</span></div>",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Se integra directamente con Canva</span></div>",
  "        </div>",
  "      </div>",
  "    </div>",
  "    <div class=\"tool-footer\">",
  "      <div class=\"platforms\"><span class=\"plat\">🌐 Web</span></div>",
  "      <span class=\"tool-tip\">💡 En el plan gratuito hay que dar crédito al autor. Canva ya los incluye si querés evitar eso.</span>",
  "      <a href=\"https://flaticon.com\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"visit-btn\">Abrir →</a>",
  "    </div>",
  "  </div>",
  "",
  "  <div class=\"tool-card bc-qr\" data-key=\"qr-code\">",
  "    <div class=\"tool-main\">",
  "      <div class=\"tool-logo lb-qr\"><span class=\"logo-emoji\">⬛</span></div>",
  "      <div class=\"tool-info\">",
  "        <div class=\"tool-header\"><span class=\"tool-name\">QR Code Generator</span><span class=\"tool-badge\">Útil</span></div>",
  "        <div class=\"tool-tagline\">Creá códigos QR personalizados para tu negocio</div>",
  "        <div class=\"tool-desc\">Generá códigos QR que lleven a tu WhatsApp, Instagram, catálogo o menú. Ideal para imprimir en packaging, volantes o tarjetas.</div>",
  "        <div class=\"tool-features\">",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>QR para cualquier link, número de WhatsApp o red social</span></div>",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Personalizá los colores para que combine con tu marca</span></div>",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Descargá en alta resolución para imprimir</span></div>",
  "        </div>",
  "      </div>",
  "    </div>",
  "    <div class=\"tool-footer\">",
  "      <div class=\"platforms\"><span class=\"plat\">🌐 Web</span></div>",
  "      <span class=\"tool-tip\">💡 Creá un QR que abra directo un chat de WhatsApp con tu número y ponelo en tus flyers.</span>",
  "      <a href=\"https://qr-code-generator.com\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"visit-btn\">Abrir →</a>",
  "    </div>",
  "  </div>",
  "</div>",
  "",
  "<!-- ══ GESTIÓN ══ -->",
  "<div class=\"category\" data-cat=\"gestion\">",
  "  <div class=\"cat-header\">",
  "    <span class=\"cat-label\">05</span>",
  "    <span class=\"cat-title\">Gestión de Redes y Negocio</span>",
  "    <div class=\"cat-line\"></div>",
  "    <span class=\"cat-count\">6</span>",
  "  </div>",
  "",
  "  <div class=\"tool-card bc-meta\" data-key=\"meta-bs\">",
  "    <div class=\"tool-main\">",
  "      <div class=\"tool-logo lb-meta\"><img src=\"https://cdn.simpleicons.org/meta/ffffff\" alt=\"Meta Business Suite\" onerror=\"this.style.display='none'\"></div>",
  "      <div class=\"tool-info\">",
  "        <div class=\"tool-header\"><span class=\"tool-name\">Meta Business Suite</span><span class=\"tool-badge\">⭐ Imprescindible</span></div>",
  "        <div class=\"tool-tagline\">Gestioná Facebook e Instagram desde un solo lugar</div>",
  "        <div class=\"tool-desc\">La herramienta oficial de Meta para gestionar tu página de Facebook y cuenta de Instagram juntas. Programá publicaciones, ve estadísticas y respondé mensajes de ambas redes en un solo lugar.</div>",
  "        <div class=\"tool-features\">",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Programá publicaciones para que se publiquen solas</span></div>",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Estadísticas de alcance e interacciones unificadas</span></div>",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Bandeja unificada para mensajes de Facebook e Instagram</span></div>",
  "        </div>",
  "      </div>",
  "    </div>",
  "    <div class=\"tool-footer\">",
  "      <div class=\"platforms\"><span class=\"plat\">🌐 Web</span><span class=\"plat\">📱 iOS</span><span class=\"plat\">🤖 Android</span></div>",
  "      <span class=\"tool-tip\">💡 Programá toda la semana el lunes — Meta las publica solas y vos te despreocupás.</span>",
  "      <a href=\"https://business.facebook.com\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"visit-btn\">Abrir →</a>",
  "    </div>",
  "  </div>",
  "",
  "  <div class=\"tool-card bc-whatsapp\" data-key=\"whatsapp-business\">",
  "    <div class=\"tool-main\">",
  "      <div class=\"tool-logo lb-whatsapp\"><img src=\"https://cdn.simpleicons.org/whatsapp/ffffff\" alt=\"WhatsApp Business\" onerror=\"this.style.display='none'\"></div>",
  "      <div class=\"tool-info\">",
  "        <div class=\"tool-header\"><span class=\"tool-name\">WhatsApp Business</span><span class=\"tool-badge\">⭐ Imprescindible</span></div>",
  "        <div class=\"tool-tagline\">El canal de ventas y atención al cliente más usado en Argentina</div>",
  "        <div class=\"tool-desc\">Una app separada de tu WhatsApp personal que convierte tu número en un perfil de negocio. Catálogo de productos, respuestas automáticas, etiquetas para organizar clientes y estadísticas de mensajes. Completamente gratis.</div>",
  "        <div class=\"tool-features\">",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Perfil de empresa con horario, dirección, web y descripción</span></div>",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Catálogo de productos con foto, precio y descripción</span></div>",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Respuestas automáticas de bienvenida y ausencia</span></div>",
  "        </div>",
  "      </div>",
  "    </div>",
  "    <div class=\"tool-footer\">",
  "      <div class=\"platforms\"><span class=\"plat\">📱 iOS</span><span class=\"plat\">🤖 Android</span></div>",
  "      <span class=\"tool-tip\">💡 Activá el catálogo — los clientes pueden ver y pedir productos sin que vos estés disponible.</span>",
  "      <a href=\"https://business.whatsapp.com\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"visit-btn\">Abrir →</a>",
  "    </div>",
  "  </div>",
  "",
  "  <div class=\"tool-card bc-google\" data-key=\"google-business\">",
  "    <div class=\"tool-main\">",
  "      <div class=\"tool-logo lb-google\"><img src=\"https://cdn.simpleicons.org/google/ffffff\" alt=\"Google Business Profile\" onerror=\"this.style.display='none'\"></div>",
  "      <div class=\"tool-info\">",
  "        <div class=\"tool-header\"><span class=\"tool-name\">Google Business Profile</span><span class=\"tool-badge\">⭐ Esencial</span></div>",
  "        <div class=\"tool-tagline\">Tu negocio en Google Maps y búsquedas de Google</div>",
  "        <div class=\"tool-desc\">Completamente gratis y muy poderoso: hace que tu negocio aparezca en Google Maps cuando buscan lo que ofrecés en tu zona. Horarios, fotos, WhatsApp y reseñas de clientes.</div>",
  "        <div class=\"tool-features\">",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Aparecés en Google Maps cuando buscan tu rubro cerca</span></div>",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Las reseñas de clientes construyen tu reputación online</span></div>",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Publicá novedades y ofertas directo en Google</span></div>",
  "        </div>",
  "      </div>",
  "    </div>",
  "    <div class=\"tool-footer\">",
  "      <div class=\"platforms\"><span class=\"plat\">🌐 Web</span><span class=\"plat\">📱 iOS</span><span class=\"plat\">🤖 Android</span></div>",
  "      <span class=\"tool-tip\">💡 Si no estás en Google Maps perdés clientes. Darse de alta es gratis y toma 10 minutos.</span>",
  "      <a href=\"https://business.google.com\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"visit-btn\">Abrir →</a>",
  "    </div>",
  "  </div>",
  "",
  "  <div class=\"tool-card bc-linktree\" data-key=\"linktree\">",
  "    <div class=\"tool-main\">",
  "      <div class=\"tool-logo lb-linktree\"><img src=\"https://cdn.simpleicons.org/linktree/ffffff\" alt=\"Linktree\" onerror=\"this.style.display='none'\"></div>",
  "      <div class=\"tool-info\">",
  "        <div class=\"tool-header\"><span class=\"tool-name\">Linktree</span><span class=\"tool-badge\">Bio de Instagram</span></div>",
  "        <div class=\"tool-tagline\">Un solo link en tu bio que lleva a todos tus canales</div>",
  "        <div class=\"tool-desc\">Instagram te deja poner solo un link en la bio. Linktree crea una página simple con todos tus links: WhatsApp, catálogo, tienda, Facebook, YouTube. El cliente elige adónde ir.</div>",
  "        <div class=\"tool-features\">",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Una URL que agrupa todos tus canales de contacto</span></div>",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Personalizás con tus colores y logo</span></div>",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Ve cuántas personas hacen click en cada link</span></div>",
  "        </div>",
  "      </div>",
  "    </div>",
  "    <div class=\"tool-footer\">",
  "      <div class=\"platforms\"><span class=\"plat\">🌐 Web</span><span class=\"plat\">📱 iOS</span><span class=\"plat\">🤖 Android</span></div>",
  "      <span class=\"tool-tip\">💡 Ponelo en tu bio y en stories con \"link en bio\" para dirigir tráfico a WhatsApp o tu tienda.</span>",
  "      <a href=\"https://linktr.ee\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"visit-btn\">Abrir →</a>",
  "    </div>",
  "  </div>",
  "",
  "  <div class=\"tool-card bc-notion\" data-key=\"notion\">",
  "    <div class=\"tool-main\">",
  "      <div class=\"tool-logo lb-notion\"><img src=\"https://cdn.simpleicons.org/notion/ffffff\" alt=\"Notion\" onerror=\"this.style.display='none'\"></div>",
  "      <div class=\"tool-info\">",
  "        <div class=\"tool-header\"><span class=\"tool-name\">Notion</span><span class=\"tool-badge\">Organización</span></div>",
  "        <div class=\"tool-tagline\">Tu calendario de contenidos y notas del negocio</div>",
  "        <div class=\"tool-desc\">Herramienta todo-en-uno para organizar tu negocio: calendario de publicaciones, ideas de contenido, pedidos, proveedores y gastos. La versión gratuita es más que suficiente.</div>",
  "        <div class=\"tool-features\">",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Calendario visual para planificar publicaciones semanales</span></div>",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Tablas para registrar pedidos, clientes y stock</span></div>",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Compartí el tablero con quien te ayude en el negocio</span></div>",
  "        </div>",
  "      </div>",
  "    </div>",
  "    <div class=\"tool-footer\">",
  "      <div class=\"platforms\"><span class=\"plat\">🌐 Web</span><span class=\"plat\">📱 iOS</span><span class=\"plat\">🤖 Android</span></div>",
  "      <span class=\"tool-tip\">💡 Una tabla simple con Día / Red / Tema / Estado ya organiza todo tu contenido.</span>",
  "      <a href=\"https://notion.so\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"visit-btn\">Abrir →</a>",
  "    </div>",
  "  </div>",
  "",
  "  <div class=\"tool-card bc-trends\" data-key=\"google-trends\">",
  "    <div class=\"tool-main\">",
  "      <div class=\"tool-logo lb-trends\"><img src=\"https://cdn.simpleicons.org/google/ffffff\" alt=\"Google Trends\" onerror=\"this.style.display='none'\"></div>",
  "      <div class=\"tool-info\">",
  "        <div class=\"tool-header\"><span class=\"tool-name\">Google Trends</span><span class=\"tool-badge\">Investigación</span></div>",
  "        <div class=\"tool-tagline\">Descubrí qué busca la gente en tu rubro y cuándo</div>",
  "        <div class=\"tool-desc\">Te muestra qué palabras busca la gente en Google, en qué momento del año hay más demanda y qué temas están creciendo. Útil para planificar tus publicaciones, promociones y estrategia de negocio.</div>",
  "        <div class=\"tool-features\">",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Filtrá por Argentina para ver tendencias locales reales</span></div>",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Descubrí en qué meses hay más demanda de tu producto</span></div>",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Comparás términos para saber cuál usar en tus publicaciones</span></div>",
  "        </div>",
  "      </div>",
  "    </div>",
  "    <div class=\"tool-footer\">",
  "      <div class=\"platforms\"><span class=\"plat\">🌐 Web</span></div>",
  "      <span class=\"tool-tip\">💡 Buscá tu rubro + \"Argentina\" para ver la estacionalidad real de tu negocio.</span>",
  "      <a href=\"https://trends.google.com\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"visit-btn\">Abrir →</a>",
  "    </div>",
  "  </div>",
  "</div>",
  "",
  "<!-- ══ VENTAS ONLINE ══ -->",
  "<div class=\"category\" data-cat=\"ventas\">",
  "  <div class=\"cat-header\">",
  "    <span class=\"cat-label\">06</span>",
  "    <span class=\"cat-title\">Tienda Online y Ventas</span>",
  "    <div class=\"cat-line\"></div>",
  "    <span class=\"cat-count\">3</span>",
  "  </div>",
  "",
  "  <div class=\"tool-card bc-tiendanube\" data-key=\"tiendanube\">",
  "    <div class=\"tool-main\">",
  "      <div class=\"tool-logo lb-tiendanube\"><span class=\"logo-emoji\">☁️</span></div>",
  "      <div class=\"tool-info\">",
  "        <div class=\"tool-header\"><span class=\"tool-name\">Tiendanube</span><span class=\"tool-badge\">⭐ Líder Argentina</span></div>",
  "        <div class=\"tool-tagline\">Tu propia tienda online en minutos, sin saber programar</div>",
  "        <div class=\"tool-desc\">La plataforma de e-commerce más usada en Argentina. Plan gratuito para empezar: subís tus productos, configurás métodos de pago (MercadoPago, transferencia) y compartís el link. Sin comisión por venta en el plan inicial.</div>",
  "        <div class=\"tool-features\">",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Tienda completa con carrito, pagos y envíos configurables</span></div>",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Integración nativa con MercadoPago, Andreani y OCA</span></div>",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Link de tienda propio para compartir por WhatsApp e Instagram</span></div>",
  "        </div>",
  "      </div>",
  "    </div>",
  "    <div class=\"tool-footer\">",
  "      <div class=\"platforms\"><span class=\"plat\">🌐 Web</span><span class=\"plat\">📱 iOS</span><span class=\"plat\">🤖 Android</span></div>",
  "      <span class=\"tool-tip\">💡 El plan gratuito no cobra comisión — solo pagás cuando escales a más funciones.</span>",
  "      <a href=\"https://www.tiendanube.com\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"visit-btn\">Abrir →</a>",
  "    </div>",
  "  </div>",
  "",
  "  <div class=\"tool-card bc-meli\" data-key=\"mercadoshops\">",
  "    <div class=\"tool-main\">",
  "      <div class=\"tool-logo lb-meli\"><span class=\"logo-emoji\">🏪</span></div>",
  "      <div class=\"tool-info\">",
  "        <div class=\"tool-header\"><span class=\"tool-name\">MercadoShops</span><span class=\"tool-badge\">Sin comisión</span></div>",
  "        <div class=\"tool-tagline\">Tu tienda propia integrada con MercadoLibre y MercadoPago</div>",
  "        <div class=\"tool-desc\">Creás una tienda online gratis vinculada a tu cuenta de MercadoLibre. Los mismos productos que vendés en ML aparecen en tu tienda propia, con el beneficio de no pagar comisión adicional por las ventas que lleguen desde ahí.</div>",
  "        <div class=\"tool-features\">",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Sin comisión por ventas que vengan de tu tienda propia</span></div>",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>MercadoPago integrado de forma nativa y automática</span></div>",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Sincronización automática con tu stock de MercadoLibre</span></div>",
  "        </div>",
  "      </div>",
  "    </div>",
  "    <div class=\"tool-footer\">",
  "      <div class=\"platforms\"><span class=\"plat\">🌐 Web</span></div>",
  "      <span class=\"tool-tip\">💡 Si ya vendés en MercadoLibre, activar MercadoShops te lleva 10 minutos y ahorrás comisiones.</span>",
  "      <a href=\"https://www.mercadoshops.com.ar\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"visit-btn\">Abrir →</a>",
  "    </div>",
  "  </div>",
  "",
  "  <div class=\"tool-card bc-mpago\" data-key=\"mercadopago\">",
  "    <div class=\"tool-main\">",
  "      <div class=\"tool-logo lb-mpago\"><span class=\"logo-emoji\">💳</span></div>",
  "      <div class=\"tool-info\">",
  "        <div class=\"tool-header\"><span class=\"tool-name\">MercadoPago</span><span class=\"tool-badge\">⭐ Esencial Argentina</span></div>",
  "        <div class=\"tool-tagline\">Cobrá con QR, link de pago o en cuotas sin tener local</div>",
  "        <div class=\"tool-desc\">La billetera digital más usada en Argentina. Gratis para emprendedores: generás un QR para cobrar en el momento, creás links de pago para compartir por WhatsApp y tus clientes pueden pagar en cuotas con tarjeta. El dinero está disponible el mismo día.</div>",
  "        <div class=\"tool-features\">",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>QR gratis para cobrar en ferias, mercados o en tu local</span></div>",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Link de pago para cobrar por WhatsApp sin que el cliente salga de la app</span></div>",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Tus clientes pueden pagar en cuotas con cualquier tarjeta</span></div>",
  "        </div>",
  "      </div>",
  "    </div>",
  "    <div class=\"tool-footer\">",
  "      <div class=\"platforms\"><span class=\"plat\">📱 iOS</span><span class=\"plat\">🤖 Android</span><span class=\"plat\">🌐 Web</span></div>",
  "      <span class=\"tool-tip\">💡 Generá un link de pago con el monto exacto y mandáselo al cliente — te paga en 30 segundos sin salir de WhatsApp.</span>",
  "      <a href=\"https://www.mercadopago.com.ar\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"visit-btn\">Abrir →</a>",
  "    </div>",
  "  </div>",
  "</div>",
  "",
  "<!-- ══ IA ══ -->",
  "<div class=\"category\" data-cat=\"ia\">",
  "  <div class=\"cat-header\">",
  "    <span class=\"cat-label\">07</span>",
  "    <span class=\"cat-title\">Inteligencia Artificial</span>",
  "    <div class=\"cat-line\"></div>",
  "    <span class=\"cat-count\">3</span>",
  "  </div>",
  "",
  "  <div class=\"tool-card bc-claude\" data-key=\"claude\">",
  "    <div class=\"tool-main\">",
  "      <div class=\"tool-logo lb-claude\"><img src=\"https://cdn.simpleicons.org/claude/ffffff\" alt=\"Claude\" onerror=\"this.style.display='none'\"></div>",
  "      <div class=\"tool-info\">",
  "        <div class=\"tool-header\"><span class=\"tool-name\">Claude</span><span class=\"tool-badge\">⭐ Recomendado</span></div>",
  "        <div class=\"tool-tagline\">La IA que mejor entiende contexto y genera textos naturales</div>",
  "        <div class=\"tool-desc\">Ideal para redactar publicaciones, responder mensajes, generar ideas de contenido y planificar tu negocio. Es la IA que mejor responde los prompts de esta guía.</div>",
  "        <div class=\"tool-features\">",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Respuestas más largas y detalladas en el plan gratuito</span></div>",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Excelente con español rioplatense y contexto argentino</span></div>",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Podés subir fotos o documentos para que los analice</span></div>",
  "        </div>",
  "      </div>",
  "    </div>",
  "    <div class=\"tool-footer\">",
  "      <div class=\"platforms\"><span class=\"plat\">🌐 Web</span><span class=\"plat\">📱 iOS</span><span class=\"plat\">🤖 Android</span></div>",
  "      <span class=\"tool-tip\">💡 Usá los prompts de la Guía de Prompts con Claude para resultados óptimos desde el primer intento.</span>",
  "      <a href=\"https://claude.ai\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"visit-btn\">Abrir →</a>",
  "    </div>",
  "  </div>",
  "",
  "  <div class=\"tool-card bc-openai\" data-key=\"chatgpt\">",
  "    <div class=\"tool-main\">",
  "      <div class=\"tool-logo lb-openai\"><img src=\"https://cdn.simpleicons.org/openai/ffffff\" alt=\"ChatGPT\" onerror=\"this.style.display='none'\"></div>",
  "      <div class=\"tool-info\">",
  "        <div class=\"tool-header\"><span class=\"tool-name\">ChatGPT</span><span class=\"tool-badge\">Popular</span></div>",
  "        <div class=\"tool-tagline\">La IA más conocida del mundo</div>",
  "        <div class=\"tool-desc\">La IA más popular. Muy buena para redactar, responder preguntas y generar ideas. La versión gratuita es suficiente para el día a día de un emprendimiento.</div>",
  "        <div class=\"tool-features\">",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Genera imágenes con DALL·E en el plan gratuito (limitado)</span></div>",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Modo de voz — hablale y te responde en voz alta</span></div>",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Miles de tutoriales disponibles para aprender a usarla</span></div>",
  "        </div>",
  "      </div>",
  "    </div>",
  "    <div class=\"tool-footer\">",
  "      <div class=\"platforms\"><span class=\"plat\">🌐 Web</span><span class=\"plat\">📱 iOS</span><span class=\"plat\">🤖 Android</span></div>",
  "      <span class=\"tool-tip\">💡 Los prompts de nuestra Guía funcionan exactamente igual en ChatGPT. Usá el que prefieras.</span>",
  "      <a href=\"https://chat.openai.com\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"visit-btn\">Abrir →</a>",
  "    </div>",
  "  </div>",
  "",
  "  <div class=\"tool-card bc-gemini\" data-key=\"gemini\">",
  "    <div class=\"tool-main\">",
  "      <div class=\"tool-logo lb-gemini\"><img src=\"https://cdn.simpleicons.org/googlegemini/ffffff\" alt=\"Gemini\" onerror=\"this.style.display='none'\"></div>",
  "      <div class=\"tool-info\">",
  "        <div class=\"tool-header\"><span class=\"tool-name\">Gemini</span><span class=\"tool-badge\">Integrado con Google</span></div>",
  "        <div class=\"tool-tagline\">La IA de Google con acceso a búsqueda en tiempo real</div>",
  "        <div class=\"tool-desc\">La IA de Google integrada con Gmail, Drive y Docs. Su ventaja es el acceso a internet en tiempo real y la integración con las herramientas de Google que ya usás.</div>",
  "        <div class=\"tool-features\">",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Acceso a internet en tiempo real — información actualizada</span></div>",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Se integra con Gmail para ayudarte a redactar y responder</span></div>",
  "          <div class=\"feat\"><span class=\"feat-icon\">→</span><span>Guardá los resultados directamente en Google Docs</span></div>",
  "        </div>",
  "      </div>",
  "    </div>",
  "    <div class=\"tool-footer\">",
  "      <div class=\"platforms\"><span class=\"plat\">🌐 Web</span><span class=\"plat\">📱 iOS</span><span class=\"plat\">🤖 Android</span></div>",
  "      <span class=\"tool-tip\">💡 Si ya usás Gmail en tu negocio, Gemini se integra naturalmente con todo lo que tenés.</span>",
  "      <a href=\"https://gemini.google.com\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"visit-btn\">Abrir →</a>",
  "    </div>",
  "  </div>",
  "</div>"
].join('\n');
